Add output in robot frame option
ros-drivers/um7 pull request #26
Opened 2020-01-06 18:32 UTC by bhomberg

We found that to use Cartographer for mapping/localization, we needed to have the IMU data output not in its default NED frame or in ENU frame, but that we needed it in robot frame (x forward, y left, z up).  This PR adds an option for robot frame output and does not change the NED or ENU output.

2020-01-28 13:32 UTC, tonybaltovski commented
The idea of a separate robot frame is kind of odd considering [REP-0103](https://www.ros.org/reps/rep-0103.html#coordinate-frame-conventions).  However, is it that you use the orientation without the magnetometer?

2020-01-28 17:51 UTC, bhomberg commented
The robot frame we're using is the one specified in the link you sent, with x forward, y left, z up.  We need the output in that frame, not relative to magnetic north (if that's what you mean by using orientation without the magnetometer).  We're using [Cartographer](https://github.com/googlecartographer/cartographer_ros) for slam, which expects IMU output in robot frame; ie, for a 2D mobile robot, only minor changes in pitch/roll and yaw is equivalent to robot orientation.

2020-01-29 21:14 UTC, tonybaltovski commented
I was trying to determine in the conditions when you would want to use the robot only frame.  Not using the magnetometer would have been one case where all data would be from the `robot_frame`. The orientation estimate from the IMU uses an EKF to fuse the magnetometer with the accelerometer and gyroscope. Thus disabling it would the orientation would be purely in the robot's frame based on its starting location.  However, this might be considered in a different PR where disabling the mag automatically places the orientation into the robot's frame.  How about changing the flag from `tf_ned_to_robot_frame` to `orientation_in_robot_frame` or something along those line?

2020-01-29 21:18 UTC, tonybaltovski requested changes

2020-01-29 21:18 UTC, tonybaltovski commented on src/main.cpp
> +enum OutputAxes
Let's follow the [roscpp style guide](http://wiki.ros.org/CppStyleGuide#Enumerations)

2020-01-29 21:18 UTC, tonybaltovski commented on src/main.cpp
> +    DEFAULT, ENU, ROBOT_FRAME
linting, two spaces please.

2020-01-29 21:18 UTC, tonybaltovski commented on src/main.cpp
> +      ROS_ERROR("Requested IMU data in two separate frames.");
linting, two spaces please.

2020-01-29 21:18 UTC, tonybaltovski commented on src/main.cpp
> +      axes = ENU;
linting, two spaces please.

2020-01-29 21:18 UTC, tonybaltovski commented on src/main.cpp
> +      axes = ROBOT_FRAME;
linting, two spaces please.

2020-02-08 01:40 UTC, bhomberg commented
Comments addressed -- ready for another look!

2020-02-10 15:59 UTC, tonybaltovski approved these changes

2020-02-10 16:00 UTC, merged

2020-02-10 16:00 UTC, tonybaltovski commented
Awesome! Thank you @bhomberg!! Let me know if you need a release.